### ISSUE TITLE
FR: dep_names

### ISSUE THREAD

**Issue by krlmlr** [richfitz/remake#103]
Same as the special `target_name` variable in rules, would contain a named list of dependencies.

Example use case: Zip multiple files.

**Comment by krlmlr** [comment]
One can also do it the other way round: Have remake autodetect the dependencies which are passed as string constants:

```r
zip_fresh <- function(zip_file, ...) {
  sources <- c(...)
  unlink(zip_file)
  zip(zip_file, sources, flags = "-3jX")
}
```

```yaml
targets:
  out.zip:
    command: zip_fresh(target_name, "file1.csv", "file2.csv")
```
