### ISSUE TITLE
changing plot properties doesn't trigger the build

### ISSUE THREAD

**Issue by fmichonneau** [richfitz/remake#104]
I had a target with:

```yaml
figures/plot1.pdf:
  command: make_figure_1()
  plot: true
```

that I updated to

```yaml
figures/plot1.pdf:
  command: make_figure_1()
  plot:
    width: 12
    height: 8
```

but that didn't trigger the re-building of the figure.
