### ISSUE TITLE
Allow diamond-style includes

### ISSUE THREAD

**Issue by krlmlr** [richfitz/remake#105]
Multiple includes of the same `.yml` currently gives `All target names must be unique`, this seems unnecessary. Example:

```yml
# base.yml
targets:
  test:
    command: quote(TRUE)

# a.yml
include:
  - base.yml

# b.yml
include:
  - base.yml

# remake.yml
include:
  - a.yml
  - b.yml
```
