### ISSUE TITLE
FR: Consider detecting changes by looking at size+timestamp only

### ISSUE THREAD

**Issue by krlmlr** [richfitz/remake#116]
Use case: Large SQLite database which I'd rather not have read entirely just to detect it hasn't changed.

Proposed syntax:

```yml
targets:
  <name>:
    check: timestamp
    command: ...
```

We also may want to consider a global option, or even making it the default. (How often does a file keep its size and mod time when contents change?)

Also, a file should be considered unchanged (with its cached timestamp information updated) if the hash is unchanged. This could also be implemented in a different `check` option.
