### ISSUE TITLE
FR: Allow scoped (double-colon) rules

### ISSUE THREAD

**Issue by krlmlr** [richfitz/remake#119]
Use case:

```yml
targets:
  <json-data>:
    command: jsonlite::fromJSON("x.json")
```

Is forbidding this an explicit design decision? Anyway, I think the error message should read:

```
Rule must be a character or name, found "jsonlite::fromJSON"
```
