### ISSUE TITLE
Does not detect changes in grouped targets 

### ISSUE THREAD

**Issue by dfalster** [richfitz/remake#129]
This issue arose [here](https://github.com/traitecoevo/plant_paper/blob/77420fba21ff91188e38b3efb31756d1c7a64c10/remake.yml#L43), but I have seen similar behaviour elsewhere. 

A nice feature of remake is the ability to group targets, e.g. if I'm writing a paper I might have a target called `figures`:

```
  figures:
    depends:
      - figures/plant.pdf
      - figures/patch.pdf
      - figures/emergent.pdf
      - figures/fitness.pdf
      - figures/schematic.pdf
```

I would have thought I could then use the `figures` target itself as a target, e.g.

```
  ms.pdf:
    command: latex_build("ms.tex", "refs.bib", clean=TRUE)
    depends:
      - figures
```

The problem is that when one of my figures changes, this change is not triggering a rebuild of `ms.pdf`. So as a result, I've been specifying the figures twice, as 

```
  figures:
    depends:
      - figures/plant.pdf
      - figures/patch.pdf
      - figures/emergent.pdf
      - figures/fitness.pdf
      - figures/schematic.pdf

  ms.pdf:
    command: latex_build("ms.tex", "refs.bib", clean=TRUE)
    depends:
      - figures/plant.pdf
      - figures/patch.pdf
      - figures/emergent.pdf
      - figures/fitness.pdf
      - figures/schematic.pdf
````
