### ISSUE TITLE
LaTeX target via pandoc

### ISSUE THREAD

**Issue by richfitz** [richfitz/remake#14]
See [here](https://github.com/dfalster/TraitGrowthTrajectories/commit/27e9c36) (private repo)

**Comment by dfalster** [comment]
Not sure it it's worth going via pandoc or using latex directly. I've succeeded in embedding latex build into maker workflow via the following. One benefit of pandoc is that hides all the latex output. But that laso make debugging harder. 

In the maker.yml

```
# convert tex to pdf
  manuscript.pdf:
    depends:
      - "references.bib"
    command: tex_2_pdf("manuscript.tex")

# make tex from Rnw file
  manuscript.tex:
    depends:
      - data
    knitr: TRUE 
```

And in source files

```
tex_2_pdf <- function(texfile){
  filename <- tools::file_path_sans_ext(texfile)
  system(sprintf("xelatex %s", texfile))
  system(sprintf("bibtex %s",   filename))
  system(sprintf("xelatex %s", texfile))
  system(sprintf("xelatex %s", texfile))
  aux.files <- paste0(filename, c(".log", ".aux", ".bbl", ".blg"))
  file.remove(aux.files[file.exists(aux.files)])
}
```
