### ISSUE TITLE
interest in an rmarkdown::render pull request?

### ISSUE THREAD

**Issue by rmflight** [richfitz/remake#152]
I've just started using `remake`, and it is awesome. Given that `rmarkdown` has really nailed going from Rmd to PDF, HTML, etc, I was thinking it would be worth having a type similar to `knitr: TRUE`, but would be `rmarkdown: TRUE` that would call `rmarkdown::render` to generate the target, and keep track of when the input file changes.

Looking at the `remake_from_knitr` code, I don't think it should be too hard.

Would such a PR be of interest?

**Comment by richfitz** [comment]
Yes, that would be great, thanks.  I am currently fairly ignorant of where the state-of-the-art is in this area, and would appreciate the help

**Comment by krlmlr** [comment]
Can we work towards a more general rule system that allows custom rules? I'm thinking about something along the following lines:

```yml
rules:
  rmd_document:
    call: knit_with_deps(target_name, dep_names)

targets:
  reports/final.html:
    type: rmd_document
    depends:
    - reports/final.Rmd
    - dep1
    - dep2
```
  
Please see also #107 for thoughts on standalone execution of documents, and https://github.com/richfitz/remake/issues/130#issuecomment-262518167 for `knit_with_deps()`.

**Comment by krlmlr** [comment]
Or maybe:

```yml
rules:
  rmd_document:
    call: knit_with_deps(target_name, dep_names)
    dep_call: figure_out_additional_knitr_deps(dep_names)

targets:
  reports/final.html:
    type: rmd_document
    depends:
    - reports/final.Rmd
```
