### ISSUE TITLE
manuscript not rebuilt when figures updated

### ISSUE THREAD

**Issue by fmichonneau** [richfitz/remake#153]
let's say I have this as `remake.yml`

```yaml
  all:
    depends: manuscript.pdf

  figures:
    depends:
      - figure1.pdf
      - figure2.pdf

  figure1.pdf:
    command: make_figure1()
    plot: true

  figure2.pdf:
    command: make_figure2()
    plot: true

  manuscript.md:
    knitr: true

  manuscript.pdf:
    depends:
      - figures
    command: render("manuscript.md")
```

this as `functions.R`

```R
myplot <- function(n, col = "blue")  {
    ggplot(data.frame(x = rnorm(n),
                      y = rnorm(n))) +
        geom_point(aes(x = x, y = y), color = col)
}

make_figure1 <- function() {
    myplot(100, "red")
}

make_figure2 <- function() {
    myplot(100, "gray50")
}
```

and this as `manuscript.Rmd`

```Rmd
---
output: pdf_document
---

![wow](figure1.pdf)

![such](figure2.pdf)
```

editing the code of make_figure1 or make_figure2 properly triggers re-building the corresponding PDF file (figure1.pdf or figure2.pdf) but not of manuscript.md:

First time this is run:

```R
> make()
<  MAKE > all
[  PLOT ] figure1.pdf    |  make_figure1() # ==> figure1.pdf
[  PLOT ] figure2.pdf    |  make_figure2() # ==> figure2.pdf
[ ----- ] figures
[  KNIT ] manuscript.md  |  knitr::knit("manuscript.Rmd", "manuscript.md")
[ BUILD ] manuscript.pdf |  render("manuscript.md")
/usr/bin/pandoc +RTS -K512m -RTS manuscript.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output manuscript.pdf --template /home/francois/.R/library/rmarkdown/rmd/latex/default-1.17.0.2.tex --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable 'geometry:margin=1in' 

Output created: manuscript.pdf
[ ----- ] all
```

2nd time without changing anything: 

```R
> make()
<  MAKE > all
[    OK ] figure1.pdf
[    OK ] figure2.pdf
[ ----- ] figures
[    OK ] manuscript.md
[    OK ] manuscript.pdf
[ ----- ] all
> make()
```

after editing the content of `make_figure2()`:

```R
> make()
[  READ ]                |  # loading sources
<  MAKE > all
[    OK ] figure1.pdf
[  PLOT ] figure2.pdf    |  make_figure2() # ==> figure2.pdf
[ ----- ] figures
[    OK ] manuscript.md
[    OK ] manuscript.pdf
[ ----- ] all
```
