### ISSUE TITLE
Script/source based targets?

### ISSUE THREAD

**Issue by noamross** [richfitz/remake#18]
This may be against the spirit of `maker`, but in struggling to move from a workflow with a series of scripts/chunks to maker, where everything is a function.  I would rather more easily re-use short scripts.

I think it may make sense for a target type to be `source` or `environment`, in which rather than a command, the target has a `source` command, and the target is a saved environment which is returned after the file is sourced. Targets depending on this target would then load that environment. e.g.

```
targets:
  processed_data:    
    source: processdata.R # The process_data target would be a saved environment

  firstplot:
    source: makeplot.R
    depends: processed_data # The process_data environment would be attached before running makeplot.R

  anobject:
    command: my_cmd()
    depends: process_data  # my_cmd() would be run in an environment with processed_data loaded. 
                            # If my_cmd takes non-target arguments (See #17), these should be able to 
                            # draw on objects in the processed_data environment.
```
