### ISSUE TITLE
Templating within a remakefile

### ISSUE THREAD

**Issue by richfitz** [richfitz/remake#2]
This is something suggested by @cboettig, and which I immediately ran into on dfalster/tree-p#9 (private repo currently).  We have a makerfile that includes targets like:

``` yaml
  output/leaf_traits.csv:
    depends: leaf_traits
    rule: export_csv
    target_argument_name: filename

  output/growth_mortality_traits.csv:
    depends: growth_mortality_traits
    rule: export_csv
    target_argument_name: filename
```

It might be nice to be able to remove the duplication in a couple of places.

Most simply, the output directory (ideally there won't be that many file targets in a maker workflow, but repetition is bad form).  The simplest option I can think of there is to use [whisker](https://github.com/edwindj/whisker), so that we'd have:

``` yaml
  {{output_dir}}/leaf_traits.csv:
    depends: leaf_traits
    rule: export_csv
    target_argument_name: filename

  {{output_dir}}/growth_mortality_traits.csv:
    depends: growth_mortality_traits
    rule: export_csv
    target_argument_name: filename
```

and then another section in the makerfile:

``` yaml
variables:
  output_dir: output
```

The only real sticking point here is that will fail miserably if a whisker variable is missing because the [mustache spec](http://mustache.github.io/mustache.5.html) says by default that missing variables result in the empty string.  [This issue](https://github.com/edwindj/whisker/issues/15) suggests that throwing errors might be a possibility.

A more complicated form of templating (which is then more prone to odd corner cases) would be to define whole template rules.  So we'd have:

```
output/{{filename}}.csv:
    depends: {{object}}
    rule: export_csv
    target_argument_name: filename
```

somehow fill that in for the two cases above.

Of course, it should be fairly easy for users to manually template their own files prior to running maker, so the simplest solution might be to trial some forms of templating outside the package and incorporate what works.

**Comment by krlmlr** [comment]
The `make` syntax would be:

```r
  output/%.csv:
    depends: %
    rule: export_csv
    target_argument_name: filename
```

Would that be an option?

**Comment by richfitz** [comment]
That's really nice, yeah.  And I like the connection to the make rules.

The use case that triggered this was slightly more complicated though (and done manually).  The repo is at [dfalster/baad](https://github.com/dfalster/baad):

* the [template](https://github.com/dfalster/baad/blob/master/config/remake_data.yml.whisker) was in whisker and required just one substitution
* we had a [bootstrap script](https://github.com/dfalster/baad/blob/master/bootstrap.R) that generated a  [fraction of a remake file](https://github.com/dfalster/baad/blob/master/remake_data.yml)
* that fraction was [included in the main remake file](https://github.com/dfalster/baad/blob/master/remake.yml#L18)

Not very pretty but it worked.

Getting the wildcard bit (#70) could work for file based patterns, but for looping over sets of objects it could all get a bit nastier.

**Comment by krlmlr** [comment]
At this point we might want to consider supporting a DSL in addition to the .yml format. It could be as simple as:

```yml
packages:
- magrittr
- tibble
- dplyr
- ggplot2

sources:
- src/

targets:
  target:
    command_to_create_target(dep1, dep2)
```

```r
remake() %>%
  add_library(c("magrittr", "tibble", "dplyr", "ggplot2)) %>%
  add_sources("src/") %>%
  add_target("target", command = ~command_to_create_target(dep1, dep2))
```

If we give the user a bit more flexibility when specifying the rules, we don't need to add all the logic ourselves. (Thanks @hadley for suggesting a DSL here.)
