### ISSUE TITLE
allow knitr targets to depend on target aliases

### ISSUE THREAD

**Issue by fmichonneau** [richfitz/remake#41]
Maybe I'm not thinking about this correctly, but It seems that it would be useful to support dependencies "aliases" in the knitr targets to avoid repetition. See `processed_data` in the example below.

```
sources:
  - code.R

targets:
  all:
    depends: plot.pdf

  processed_data:
     depends:
        - processed_data_1
        - processed_data_2
        - processed_data_3

  data.csv:
    command: download_data(target_name)

  processed_data_1:
    command: process_data("data1.csv")

  processed_data_2:
    command: process_data("data2.csv")

  processed_data_3:
    command: processed_data_alt("data1.csv")

  plot.pdf:
    command: myplot(processed)
    plot: true

  report.md:
    depends:
      - processed_data
    knitr: true
```
