### ISSUE TITLE
Determine rule/args from command

### ISSUE THREAD

**Issue by richfitz** [richfitz/remake#6]
Replace things like

``` yaml
  growth_mortality_traits:
    depends: download/wright_2010.txt
    rule: process_wright_2010
```

with

``` yaml
 growth_mortality_traits:
    command: process_wright_2010("download/wright_2010.txt")
```

or more generally 

``` yaml
target:
  depends: [foo, bar]
  rule: func
```

with

```
target:
  command: func(foo, bar)
```

Retain, at least for now the current `depends:` / `rule:` interface.  An explicit `depends` will be needed for fake targets anyway.

The inverse problem to `target_argument_name` appears: how to pass in the name of the target into the function.  Doing that manually is of course possible:

``` yaml
target.csv:
  command: f("target.csv")
```

But better would be to allow `.` (following dplyr) and/or more explicitly:

``` yaml
target.csv:
  command: f(target_name)
```
