### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by richfitz** [richfitz/remake#66]
With this set up:

```
packages: rmarkdown
targets:
  manuscript.docx:
    command: render("manuscript.Rmd", "word_document", "manuscript.docx")
    depends: figures
```

The error message generated is:

```
Error in .remake_add_targets_implied(obj) : 
  Implicitly created targets must all be files:
 - word_document: (in manuscript.docx)
```

because `word_document` should be in `I()`.  Perhaps link message to a helpfile that describes `I` and implicit targets.  Perhaps *suggest* `I` if no extension is present on the name.
