### ISSUE TITLE
check knitr options

### ISSUE THREAD

**Issue by richfitz** [richfitz/remake#67]
Wrong, but no warning:

```
  MS/SuppMatt.md:
    knitr: 
      options: 
        auto_figure_prefix: true
        chdir: true
```

```
  MS/SuppMatt.md:
    knitr: 
      auto_figure_prefix: true
      chdir: true
```

docs need clearing up https://github.com/richfitz/remake/blob/master/doc/format.md#knitr-targets

@aammd
