### ISSUE TITLE
error calling function 

### ISSUE THREAD

**Issue by lukemac1** [richfitz/remake#74]
My apologies if this is an error in my programming, but I am new to using remake and am hopeful it will be a useful tool for me.  I've created a simple makefile to run a function:

```
packages:
  - sp
  - rgeos
  - rgdal
  - ineq
  - raster

sources:
  - functions/gini.calc.R
  
targets:
  all:
    depends: outputs/gini-coefficients-all-land-by-Bioregion(Omernik).csv
      
  ownfix: 
    command: load(file = "d:/BoxSync/Ownership-Analysis/data/Clean.Ownership.Map-gBuffer.rdata")
    
  bioregions:
    command: readOGR(dsn = I("D:/BoxSync/Ownership-Analysis/data/bioregions"), layer= I("CA_Omernik(NAD83)")) 

  gini_list_bioregions:
    command: gini.calc.bioregion.LEVEL3_NAM(bioregions, ownfix)
    
  outputs/gini-coefficients-all-land-by-Bioregion(Omernik).csv:
    command: write.csv(gini_list_bioregions, file = "outputs/gini-coefficients-all-land-by-Bioregion(Omernik).csv")
```
It seems to be working fine up until the function `gini.calc.bioregion.LEVEL3_NAM()`, where I get an error: 
```
> remake::make()
[  READ ]                                                              |  # loading sources
<  MAKE > all
[    OK ] bioregions
[    OK ] ownfix
[ BUILD ] gini_list_bioregions                                         |  gini_list_bioregions <- gini.calc.bioregion.LE...
[  READ ]                                                              |  # loading packages
 
 Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘extent’ for signature ‘"character"’ 
```
That function calls on a data column name from a spatialpolygonsdataframe titled "LEVEL3_NAM" (see below), which I think is causing my problem. I have currently put the column name into the function, but previously had it as a character parameter in the function in quotation marks. The function works both ways in regular R, but it seems to be having a problem when running through `remake::make()`  Both ways returns this error.  The function is here:

```
gini.calc.bioregion.LEVEL3_NAM <- function(regionboundaries, ownership){ 
  #regionboundaries is a spatialpolygons file associated with regionboundaries
  #ownership is spatial data that is used in assessing the gini calculation
 
  regionnames <- unique(regionboundaries@data[,"LEVEL3_NAM"]) #I believe this may be causing the problem as well as further below
  
  gini.list <- as.data.frame(matrix(0, ncol = 2, nrow = length(regionnames)))
  gini.list[,1]<-regionnames
  row.names(gini.list) <- regionnames
  colnames(gini.list) <- c("Region","Gini.Coeff")
  
  #running through all the regions found in the data column titled "LEVEL3_NAM"
  for (i in regionnames){
    regionbound <- regionboundaries[regionboundaries@data[,"LEVEL3_NAM"] == i,]
    inter <- intersect(regionbound, ownership)
    inter.area.list <- gArea(inter, byid=TRUE)
    gini.list[i,2]  <- ineq(inter.area.list, type = "Gini")
  } 
  return(gini.list)
}
```
Any suggestions?  I was thinking about having the function call on the column number of interest and avoid the use of calling by character column name since it seems like the error is taking issue with that. Maybe I'll try that tomorrow.

Maybe this is muddying the waters, but I also found other strange problems like it throwing this error if I used file.path() in my readOGR call... 
```
Error in FUN(X[[i]], ...) : While processing target 'bioregions':
    Unknown special function file.path
```
I worked around it in that case by using `I("D:/filpathhere")`, which I saw in another issue, but am a bit unclear on why it's not translating the `file.path()` function over, but it will use the file path from `load()` without a problem.
