### ISSUE TITLE
Fake targets do not propagate downstream rebuilds in simple example.

### ISSUE THREAD

**Issue by wlandau** [richfitz/remake#92]
In this example, I have `code.R`

```r
my_mtcars = function(){
  data(mtcars)
  mtcars
}

my_random = function(){
  data.frame(y = rnorm(31))
}

my_plot = function(mtcars, random){
  plot(mtcars$mpg, random$y)
}
```

and `remake.yml`.

```yaml
sources: code.R

targets:

  all:
    depends: report.md

  report.md:
    knitr: TRUE
    depends: datasets

  datasets:
    depends:
      - mtcars
      - random

  mtcars:
    command: my_mtcars()

  random:
    command: my_random()
```

I want to use the `datasets` fake target instead of having to write `mtcars` and `random` individually. My first problem is that `random` is not automatically loaded into my knitr report `report.Rmd` below, but that's another story.

```r
head(mtcars)
# head(random) # Error in head(random) : object 'random' not found
```

The first time I run the project, everything looks fine.

```r
> remake::make()
<  MAKE > all
[ BUILD ] mtcars    |  mtcars <- my_mtcars()
[ BUILD ] random    |  random <- my_random()
[ ----- ] datasets
[  KNIT ] report.md |  knitr::knit("report.Rmd", "report.md")
[ ----- ] all
```

But when I change the contents of `my_mtcars()` and run the project again, the report is not re-knitted. 

```r
> make()
[  READ ]           |  # loading sources
<  MAKE > all
[ BUILD ] mtcars    |  mtcars <- my_mtcars()
[    OK ] random
[ ----- ] datasets
[    OK ] report.md
[ ----- ] all
> 
```

Since GNU Make uses timestamps, this issue is unavoidable with traditional phony targets. But with `remake`'s hashing system, it seems possible to allow downstream rebuilds to be triggered through fake targets.
